### ISSUE TITLE
Elixir.webpack.mergeConfig  How I want to configure is right

### ISSUE THREAD

**Issue by bigrocs** [JeffreyWay/laravel-elixir-webpack-official#29]
```
Elixir.webpack.mergeConfig({
    babel: {
        presets: ['es2015'],
        plugins: ['add-module-exports', 'transform-runtime'],
    },
    module: {
        loaders: [{
            test: /\.vue$/,
            loader: 'vue'
        }]
    }
});  
```

`TypeError: Cannot read property 'mergeConfig' of undefined
    at Object.<anonymous> (D:\phpStudy\WWW\laravelvue\gulpfile.js:13:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at execute (C:\Users\Administrator\AppData\Roaming\npm\node_modules\.gulp-cli_npminstall\node_modules\.1.2.2@gulp-cli\lib\versioned\^3.7.0\index.js
:24:18)``

**Comment by bigrocs** [comment]
Cannot read property 'mergeConfig' of undefined at Object

**Comment by JeanLucEsser** [comment]
DO you do that in your Gulp file?
If so, did you `require('laravel-elixir-webpack-official');` so that `Elixir.webpack` is defined?

**Comment by Fatih90** [comment]
@JeanLucEsser now it says `Cannot find module 'laravel-elixir-webpack-official`

**Comment by bigrocs** [comment]
thanks 
The problem has already been solved.

require('laravel-elixir-webpack-official');
Elixir.webpack.config.module.loaders = [];
